# Generated by Django 6.0.3 on 2026-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_document_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sticker',
            field=models.BooleanField(default=False),
        ),
    ]
