# Generated by Django 6.0.3 on 2026-04-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_status_statusview'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_status_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_messages', to='chat.status'),
        ),
    ]
