# Generated by Django 6.0.3 on 2026-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_is_status_reply_message_status_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBillboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('image', 'Sawir'), ('video', 'Muuqaal'), ('audio', 'Cod'), ('quiz', 'Su’aalo Quiz ah')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='billboard/')),
                ('link', models.URLField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
