# Generated by Django 6.0.3 on 2026-04-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_globalbillboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalbillboard',
            name='content_type',
            field=models.CharField(choices=[('image', 'Sawir'), ('video', 'Muuqaal'), ('audio', 'Cod'), ('quiz', 'Su’aalo Quiz ah'), ('document', 'PDF ama Buug')], max_length=10),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(help_text='Gali 1, 2, 3 ama 4 (Jawaabta saxda ah)')),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chat.globalbillboard')),
            ],
        ),
    ]
