# Generated by Django 6.0.3 on 2026-04-10 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_globalbillboard_content_type_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_by_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteMessage',
        ),
    ]
