# Generated by Django 6.0.3 on 2026-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_starred_by_alter_message_deleted_by_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_love_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
