# Generated by Django 6.0.3 on 2026-04-11 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_is_love_reaction_message_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='to_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='to_system_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='badge_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', help_text='Magaca saddexan ee qofka', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_account_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='system_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
