# Generated by Django 6.0.3 on 2026-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_profile_image_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
