# Generated by Django 6.0.3 on 2026-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_profile_profile_pic_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge_type',
            field=models.IntegerField(default=3),
        ),
    ]
